from typing import Tuple
from numpy.typing import NDArray

def cuda_matmul(a:NDArray, b:NDArray) -> NDArray:...
def cuda_conv2d_forward(a: NDArray, w: NDArray, stride: int, padding: int) -> NDArray:...
def cuda_conv2d_backward(a: NDArray, w: NDArray, stride: int, padding: int, grad: NDArray) -> Tuple[NDArray, NDArray]:...